name: Provider Integration Tests
on:
  workflow_call:
    inputs:
      skip_setup:
        description: Skip the version and build step and use parent
        default: false
        required: false
        type: boolean
      concurrency_group_prefix:
        default: pr
        required: false
        type: string
      terraform_version:
        description: Version of Terraform to use
        default: 1.6.5
        type: string
        required: false
      dist_artifact_name:
        description: Name of the dist artifact created
        default: dist-provider-integration
        required: false
        type: string

concurrency:
  group: ${{ inputs.concurrency_group_prefix }}-provider-integration-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  prepare-provider-tests:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.build-provider-test-matrix.outputs.tests }}
    container:
      image: terraconstructs/jsii-terraform@sha256:c46ac91c8be20947a2b0e27a517eb4a5bfc015c16a27341876ed0b04d734ddf5
    env:
      CHECKPOINT_DISABLE: "1"
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: "Add Git safe.directory" # Go 1.18+ started embedding repo info in the build and e.g. building @cdktn/hcl2json fails without this
        run: git config --global --add safe.directory /__w/cdk-terrain/cdk-terrain
      - name: ensure correct user
        run: chown -R root /__w/cdk-terrain
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
      # Setup caches for yarn, and go
      - name: Get cache directory paths
        id: global-cache-dir-path
        run: |
          echo "yarn=$(yarn cache dir)" >> $GITHUB_OUTPUT
          mkdir -p /usr/local/share/.cache/go
          echo "go=/usr/local/share/.cache/go" >> $GITHUB_OUTPUT
      - name: Restore yarn cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.global-cache-dir-path.outputs.yarn }}
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-provider-integration
          restore-keys: |
            yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-
            yarn-${{ runner.os }}-
      - name: Restore go cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.global-cache-dir-path.outputs.go }}
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}-provider-integration
          restore-keys: |
            go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}-
            go-${{ runner.os }}-
      - name: installing dependencies and build
        if: ${{ !inputs.skip_setup }}
        run: |
          yarn install --frozen-lockfile --prefer-offline
          yarn build
          yarn package
        env:
          GOCACHE: ${{ steps.global-cache-dir-path.outputs.go }}
      - name: installing test dependencies
        run: |
          cd test && yarn install --frozen-lockfile --prefer-offline
      - name: Upload dist
        if: ${{ !inputs.skip_setup }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.dist_artifact_name }}
          path: dist
      - name: Build provider test matrix
        id: build-provider-test-matrix
        run: node tools/build-provider-test-matrix.mjs

  linux_provider:
    needs: prepare-provider-tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.prepare-provider-tests.outputs.tests)}}
    container:
      image: terraconstructs/jsii-terraform@sha256:c46ac91c8be20947a2b0e27a517eb4a5bfc015c16a27341876ed0b04d734ddf5
    env:
      CHECKPOINT_DISABLE: "1"
      TERRAFORM_VERSION: ${{ inputs.terraform_version }}
      TERRAFORM_BINARY_NAME: "terraform${{ inputs.terraform_version }}"
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Download dist
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ inputs.dist_artifact_name }}
          path: dist
      - name: ensure correct user
        run: chown -R root /__w/cdk-terrain
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
      - name: Get cache directory paths
        id: global-cache-dir-path
        run: |
          echo "yarn=$(yarn cache dir)" >> $GITHUB_OUTPUT
          mkdir -p "${RUNNER_TEMP}/terraform-cache"
          echo "terraform=${RUNNER_TEMP}/terraform-cache" >> $GITHUB_OUTPUT
      # Only restoring yarn caches as the dependencies are not indiviual to each matrix job
      - name: Restore yarn cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.global-cache-dir-path.outputs.yarn }}
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-provider-integration
          restore-keys: |
            yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-
            yarn-${{ runner.os }}-
      - name: Restore terraform plugin cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.global-cache-dir-path.outputs.terraform }}
          key: terraform-${{ runner.os }}-${{ inputs.terraform_version }}-provider-integration
          restore-keys: |
            terraform-${{ runner.os }}-${{ inputs.terraform_version }}-
      - name: install test dependencies
        run: cd test && yarn install --frozen-lockfile --prefer-offline
      - name: integration tests
        run: cd test && npm run test:provider -- ${TEST_TARGET}
        env:
          TEST_TARGET: ${{ matrix.target }}
          NODE_OPTIONS: "--max-old-space-size=7168"
          TF_PLUGIN_CACHE_DIR: ${{ steps.global-cache-dir-path.outputs.terraform }}
          SYNTH_HCL_OUTPUT: ${{ matrix.hclOutput }}

  windows_provider:
    needs: prepare-provider-tests
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.prepare-provider-tests.outputs.tests)}}
    env:
      CHECKPOINT_DISABLE: "1"
      TERRAFORM_VERSION: ${{ inputs.terraform_version }}
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e
        with:
          terraform_wrapper: false
          terraform_version: ${{ inputs.terraform_version }}
      - name: Download dist
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ inputs.dist_artifact_name }}
          path: dist
      - name: Get cache directory paths
        id: global-cache-dir-path
        shell: bash
        run: |
          echo "yarn=$(yarn cache dir)" >> $GITHUB_OUTPUT
          mkdir -p "${RUNNER_TEMP}/terraform-cache"
          echo "terraform=${RUNNER_TEMP}/terraform-cache" >> $GITHUB_OUTPUT
      # Only restoring yarn caches to save available cache storage size
      - name: Restore yarn cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.global-cache-dir-path.outputs.yarn }}
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-provider-integration
          restore-keys: |
            yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-
            yarn-${{ runner.os }}-
      - name: Restore terraform plugin cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ steps.global-cache-dir-path.outputs.terraform }}
          key: terraform-${{ runner.os }}-${{ inputs.terraform_version }}-provider-integration
          restore-keys: |
            terraform-${{ runner.os }}-${{ inputs.terraform_version }}-
      # tmp fix for https://github.com/npm/cli/issues/4980
      - name: update npm
        run: npm install -g npm@8.12.1
      - name: install test dependencies
        run: cd test && yarn install --frozen-lockfile --prefer-offline
      - name: integration tests
        run: cd test && ./provider-tests/test-provider.bat ${env:TEST_TARGET}
        env:
          TEST_TARGET: ${{ matrix.target }}
          NODE_OPTIONS: "--max-old-space-size=7168"
          TF_PLUGIN_CACHE_DIR: ${{ steps.global-cache-dir-path.outputs.terraform }}
          SYNTH_HCL_OUTPUT: ${{ matrix.hclOutput }}
