name: Quality
on:
  merge_group:
    types: [checks_requested]
  workflow_call:
    inputs:
      concurrency_group_prefix:
        default: pr
        required: false
        type: string

concurrency:
  group: ${{ inputs.concurrency_group_prefix }}-quality-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    container:
      image: terraconstructs/jsii-terraform@sha256:c46ac91c8be20947a2b0e27a517eb4a5bfc015c16a27341876ed0b04d734ddf5
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
      - name: installing dependencies
        run: |
          yarn install --frozen-lockfile
      - name: run prettier
        run: |
          yarn lint:prettier

  lint:
    runs-on: ubuntu-latest
    container:
      image: terraconstructs/jsii-terraform@sha256:c46ac91c8be20947a2b0e27a517eb4a5bfc015c16a27341876ed0b04d734ddf5
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: "Add Git safe.directory"
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
      - name: Derive SHAs for nx affected
        uses: nrwl/nx-set-shas@38457b511e60ee4e1da09255b658e480748a1af4 # v5.0.1
      - name: installing dependencies
        run: |
          yarn install --frozen-lockfile
      - name: run lint (affected)
        if: github.event_name == 'pull_request'
        run: |
          yarn nx affected -t lint --parallel=3 --format=gha --base="$NX_BASE" --head="$NX_HEAD"
      - name: run lint (all)
        if: github.event_name != 'pull_request'
        run: |
          yarn nx run-many -t lint --parallel=3 --format=gha
      - name: lint examples
        run: yarn lint:examples

  knip:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: run knip
        run: yarn knip --reporter github-actions --reporter symbols
